spring.application.name=interviewace

spring.datasource.url=jdbc:postgresql://localhost:5432/interviewace
spring.datasource.username=postgres
spring.datasource.password=Abnm123@#$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080

Jwt.secretkey=nvpwoe9wvmcw282kfoekcc6ccdc5m23mkfc4cmcmckckwniiccksw5fm3kc8cmjcckcm